name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  setup:
    name: Setup - Main
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.generate.outputs.modules }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: MAIN - Generate module list
        id: generate
        run: |
          modules=$(grep '^include("' settings.gradle.kts | grep -v gallery | sed 's/include("://' | sed 's/")//' | jq -R . | jq -s . | tr -d '\n')
          echo "modules=$modules" >> $GITHUB_OUTPUT

  publish-dry:
    name: Dry run publish - Main
    needs: setup
    strategy:
      matrix:
        module: ${{ fromJson(needs.setup.outputs.modules) }}
    runs-on: ubuntu-latest
    environment: maven-central
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - uses: gradle/actions/wrapper-validation@v3
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/gradle-wrapper.properties', '**/*.gradle*', '**/gradle.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: MAIN DRY RUN - Compile ${{ matrix.module }}
        run: ./gradlew --no-daemon --console=plain :${{ matrix.module }}:assemble

      - name: MAIN DRY RUN - Publish ${{ matrix.module }}
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
        run: ./gradlew :${{ matrix.module }}:publishAllPublicationsToMavenCentral --no-configuration-cache --dry-run

  publish-mavenLocal:
    name: Maven local publish - Main
    needs: setup
    strategy:
      matrix:
        module: ${{ fromJson(needs.setup.outputs.modules) }}
    runs-on: ubuntu-latest
    environment: maven-central
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - uses: gradle/actions/wrapper-validation@v3
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/gradle-wrapper.properties', '**/*.gradle*', '**/gradle.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: MAIN LOCAL - Compile ${{ matrix.module }}
        run: ./gradlew --no-daemon --console=plain :${{ matrix.module }}:assemble

      - name: MAIN LOCAL - Publish ${{ matrix.module }}
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
        run: ./gradlew :${{ matrix.module }}:publishToMavenLocal --no-configuration-cache
